# Created using wingetcreate 1.2.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: AcroSoftwareInc.CutePDFWriter
PackageVersion: 4.0.1.2
PackageLocale: en-US
Publisher: Acro Software Inc.
PackageName: CutePDF Writer
License: proprietary
Copyright: Copyright © 2003-2022 Acro Software Inc.
ShortDescription: Create PDFs from almost any application
ManifestType: defaultLocale
ManifestVersion: 1.4.0
